### PR TITLE
dask_labextension v5.0.2, remove dependency on nodejs, more tests and maintainer

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Thanks for maintaining this, folks!

This (sorta) simplifies the recipe:
- removing the `nodejs` dependency altogether 
- deletes `pyproject.toml`
- uses the `--skip-npm` flag

Then makes it more complicated:
- checks to ensure the extension is installed
- checks to ensure the `plugin.json` gets gets deployed (my original issue)

```js
Uncaught (in promise) Error: Schema not found: /zzz/share/jupyter/lab/schemas/dask-labextension/plugin.json
    at Function.create (jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2)
    at async a.fetch (jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2)
```

- adds me as a co-maintainer... not in any braggin' kinda way, but i do keep the ship running on about half the core jupyter conda-forge stuff and a stable of labextensions as long as my arm, so am happy to help out here! one of these days we'll figure out the right pattern https://github.com/conda-forge/conda-forge.github.io/issues/1421

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/dask_labextension ready for review!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by jsignell** [comment]
@ian-r-rose @jacobtomlinson you probably have more insight. I can also add you to the maintainer list if you like.

**Comment by bollwyvl** [comment]
> add you to the maintainer list 

Happy to help!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by ian-r-rose** [comment]
Thanks for this @bollwyvl!

>     * removing the `nodejs` dependency altogether

:+1: 

>     * deletes `pyproject.toml`
>     * uses the `--skip-npm` flag


I admit I'm still a little puzzled as to what best practices are between PEP 517/518 packaging and conda-forge packaging (especially for labextensions and `jupyter-packaging`). Can you elaborate a bit on these?

>     * checks to ensure the `plugin.json` gets gets deployed (my original issue)

Thanks for this. Fixes dask/dask-labextension#191

**Comment by bollwyvl** [comment]
> puzzled as to what best practices

Yeah, right? Honestly: I don't really know. 

It's a non-secret that i'm not a big fan of `jupyter-packaging` (or really `jupyter-*` that isn't _directly_ related to the interactive computing experience), and my grumbling has at least gotten it _out_ of a number of `run` dependencies, as that was already starting to cause problems.

But wait, it's not just `jupyter-packaging`! This is a problem with `poetry`-based packages as well.... even though  `PIP_NO_BUILD_ISOLATION=1` is set, it still sometimes seems to escape, and ends up shipping rando junk in the package. `flit` seems to Just Work, but then, it doesn't try to reinvent the.... wheel (groan), just implement the spec as closely as possible _and_ offer a backwards-compatible `setup.py` in sdists. But `flit` probably won't support `data_files` unless the situation gets _much_ better, and our explorations of alternatives to the _mechanism_ have been... disheartening https://github.com/jupyter-server/jupyter_server/issues/351

Probably at the end of the day, conda-build will have to start patching `pyproject.toml`, but until then, gotta keep shipping!

**Comment by ian-r-rose** [comment]
I'm happy with this if CI is happy, but if @ocefpaf has any thoughts around `pyproject.toml`, I'd be curious to hear them

**Comment by ocefpaf** [comment]
> I'm happy with this if CI is happy, but if @ocefpaf has any thoughts around `pyproject.toml`, I'd be curious to hear them

Sometimes it works as-is, sometimes the build dependencies listed there force us to delete it and let conda take care of the build. I agree with @bollwyvl, this is something that should be fixed in conda-build. Until then, we need the workaround in some places.

**Comment by ian-r-rose** [comment]
Thanks @ocefpaf

**Comment by bollwyvl** [comment]
Thanks all!

**Pull request merged**
